# Generated by Django 4.2.11 on 2024-05-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=10)),
                ('comuna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='inmofacil_app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario')], max_length=20)),
                ('direccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='inmofacil_app.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('inmueble_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('m2_contruidos', models.CharField(max_length=20)),
                ('m2_terreno', models.CharField(max_length=20)),
                ('cantidad_estacionamiento', models.CharField(max_length=10)),
                ('cantidad_baños', models.CharField(max_length=10)),
                ('tipo_inmueble', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], max_length=20)),
                ('valor_mensual', models.FloatField(max_length=50)),
                ('direccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='inmofacil_app.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna', to='inmofacil_app.region'),
        ),
    ]
