# Generated by Django 4.2.11 on 2024-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmofacil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='foto_url',
            field=models.URLField(default='https://static3.depositphotos.com/1000647/119/i/450/depositphotos_1191873-stock-photo-house.jpg'),
            preserve_default=False,
        ),
    ]
