# Generated by Django 4.2.11 on 2024-06-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmofacil_app', '0002_inmueble_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='foto_url',
            field=models.URLField(max_length=500),
        ),
    ]
