# Generated by Django 4.2.11 on 2024-06-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmofacil_app', '0004_alter_inmueble_foto_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='mail',
            new_name='email',
        ),
    ]
